[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.lld",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.lld",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
